In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
teams = [
    {"rank": 1,  "team": "France",             "group": "I", "rating": 1877.32},
    {"rank": 2,  "team": "Spain",              "group": "H", "rating": 1876.40},
    {"rank": 3,  "team": "Argentina",          "group": "J", "rating": 1874.81},
    {"rank": 4,  "team": "England",            "group": "L", "rating": 1825.97},
    {"rank": 5,  "team": "Portugal",           "group": "K", "rating": 1763.83},
    {"rank": 6,  "team": "Brazil",             "group": "C", "rating": 1761.16},
    {"rank": 7,  "team": "Netherlands",        "group": "F", "rating": 1757.87},
    {"rank": 8,  "team": "Morocco",            "group": "C", "rating": 1755.87},
    {"rank": 9,  "team": "Belgium",            "group": "G", "rating": 1734.71},
    {"rank": 10, "team": "Germany",            "group": "E", "rating": 1730.37},
    {"rank": 11, "team": "Croatia",            "group": "L", "rating": 1717.07},
    {"rank": 13, "team": "Colombia",           "group": "K", "rating": 1693.09},
    {"rank": 14, "team": "Senegal",            "group": "I", "rating": 1688.99},
    {"rank": 15, "team": "Mexico",             "group": "A", "rating": 1681.03},
    {"rank": 16, "team": "USA",                "group": "D", "rating": 1673.13},
    {"rank": 17, "team": "Uruguay",            "group": "H", "rating": 1673.07},
    {"rank": 18, "team": "Japan",              "group": "F", "rating": 1660.43},
    {"rank": 19, "team": "Switzerland",        "group": "B", "rating": 1649.40},
    {"rank": 22, "team": "Ecuador",            "group": "E", "rating": 1610.53},
    {"rank": 24, "team": "South Korea",        "group": "A", "rating": 1594.35},
    {"rank": 25, "team": "Turkey",             "group": "D", "rating": 1586.79},
    {"rank": 26, "team": "Australia",          "group": "D", "rating": 1581.22},
    {"rank": 27, "team": "Norway",             "group": "I", "rating": 1572.46},
    {"rank": 28, "team": "Austria",            "group": "J", "rating": 1568.91},
    {"rank": 29, "team": "Sweden",             "group": "F", "rating": 1551.34},
    {"rank": 30, "team": "Tunisia",            "group": "F", "rating": 1530.18},
    {"rank": 31, "team": "Iran",               "group": "G", "rating": 1521.43},
    {"rank": 32, "team": "Saudi Arabia",       "group": "H", "rating": 1510.87},
    {"rank": 33, "team": "Canada",             "group": "B", "rating": 1500.64},
    {"rank": 34, "team": "Scotland",           "group": "C", "rating": 1491.22},
    {"rank": 35, "team": "Algeria",            "group": "J", "rating": 1478.56},
    {"rank": 37, "team": "Ivory Coast",        "group": "E", "rating": 1461.83},
    {"rank": 38, "team": "Paraguay",           "group": "D", "rating": 1449.27},
    {"rank": 39, "team": "Egypt",              "group": "G", "rating": 1438.91},
    {"rank": 40, "team": "South Africa",       "group": "A", "rating": 1401.56},
    {"rank": 43, "team": "Bosnia-Herzegovina", "group": "B", "rating": 1389.43},
    {"rank": 44, "team": "Ghana",              "group": "L", "rating": 1378.62},
    {"rank": 47, "team": "Panama",             "group": "L", "rating": 1361.44},
    {"rank": 48, "team": "Qatar",              "group": "B", "rating": 1340.21},
    {"rank": 51, "team": "Jordan",             "group": "J", "rating": 1271.38},
    {"rank": 52, "team": "Iraq",               "group": "I", "rating": 1258.73},
    {"rank": 55, "team": "Cape Verde",         "group": "H", "rating": 1241.56},
    {"rank": 58, "team": "Congo DR",           "group": "K", "rating": 1229.84},
    {"rank": 61, "team": "Uzbekistan",         "group": "K", "rating": 1198.43},
    {"rank": 72, "team": "New Zealand",        "group": "G", "rating": 1281.34},
    {"rank": 78, "team": "Haiti",              "group": "C", "rating": 1201.67},
    {"rank": 85, "team": "Curacao",            "group": "E", "rating": 1098.32},
]

In [4]:
new_df=pd.DataFrame(teams)

In [5]:
new_df

    rank                team group   rating
0      1              France     I  1877.32
1      2               Spain     H  1876.40
2      3           Argentina     J  1874.81
3      4             England     L  1825.97
4      5            Portugal     K  1763.83
5      6              Brazil     C  1761.16
6      7         Netherlands     F  1757.87
7      8             Morocco     C  1755.87
8      9             Belgium     G  1734.71
9     10             Germany     E  1730.37
10    11             Croatia     L  1717.07
11    13            Colombia     K  1693.09
12    14             Senegal     I  1688.99
13    15              Mexico     A  1681.03
14    16                 USA     D  1673.13
15    17             Uruguay     H  1673.07
16    18               Japan     F  1660.43
17    19         Switzerland     B  1649.40
18    22             Ecuador     E  1610.53
19    24         South Korea     A  1594.35
20    25              Turkey     D  1586.79
21    26           Australia     D  1581.22
22    27              Norway     I  1572.46
23    28             Austria     J  1568.91
24    29              Sweden     F  1551.34
25    30             Tunisia     F  1530.18
26    31                Iran     G  1521.43
27    32        Saudi Arabia     H  1510.87
28    33              Canada     B  1500.64
29    34            Scotland     C  1491.22
30    35             Algeria     J  1478.56
31    37         Ivory Coast     E  1461.83
32    38            Paraguay     D  1449.27
33    39               Egypt     G  1438.91
34    40        South Africa     A  1401.56
35    43  Bosnia-Herzegovina     B  1389.43
36    44               Ghana     L  1378.62
37    47              Panama     L  1361.44
38    48               Qatar     B  1340.21
39    51              Jordan     J  1271.38
40    52                Iraq     I  1258.73
41    55          Cape Verde     H  1241.56
42    58            Congo DR     K  1229.84
43    61          Uzbekistan     K  1198.43
44    72         New Zealand     G  1281.34
45    78               Haiti     C  1201.67
46    85             Curacao     E  1098.32

In [6]:
new_df.shape

(47, 4)

In [7]:
v={"rank": 36, "team": "Czechia", "group": "A", "rating": 1471.24}

In [8]:
new_df=pd.concat([new_df,pd.DataFrame([v])],ignore_index=True)

In [9]:
new_df

    rank                team group   rating
0      1              France     I  1877.32
1      2               Spain     H  1876.40
2      3           Argentina     J  1874.81
3      4             England     L  1825.97
4      5            Portugal     K  1763.83
5      6              Brazil     C  1761.16
6      7         Netherlands     F  1757.87
7      8             Morocco     C  1755.87
8      9             Belgium     G  1734.71
9     10             Germany     E  1730.37
10    11             Croatia     L  1717.07
11    13            Colombia     K  1693.09
12    14             Senegal     I  1688.99
13    15              Mexico     A  1681.03
14    16                 USA     D  1673.13
15    17             Uruguay     H  1673.07
16    18               Japan     F  1660.43
17    19         Switzerland     B  1649.40
18    22             Ecuador     E  1610.53
19    24         South Korea     A  1594.35
20    25              Turkey     D  1586.79
21    26           Australia     D  1581.22
22    27              Norway     I  1572.46
23    28             Austria     J  1568.91
24    29              Sweden     F  1551.34
25    30             Tunisia     F  1530.18
26    31                Iran     G  1521.43
27    32        Saudi Arabia     H  1510.87
28    33              Canada     B  1500.64
29    34            Scotland     C  1491.22
30    35             Algeria     J  1478.56
31    37         Ivory Coast     E  1461.83
32    38            Paraguay     D  1449.27
33    39               Egypt     G  1438.91
34    40        South Africa     A  1401.56
35    43  Bosnia-Herzegovina     B  1389.43
36    44               Ghana     L  1378.62
37    47              Panama     L  1361.44
38    48               Qatar     B  1340.21
39    51              Jordan     J  1271.38
40    52                Iraq     I  1258.73
41    55          Cape Verde     H  1241.56
42    58            Congo DR     K  1229.84
43    61          Uzbekistan     K  1198.43
44    72         New Zealand     G  1281.34
45    78               Haiti     C  1201.67
46    85             Curacao     E  1098.32
47    36             Czechia     A  1471.24

In [10]:
new_df=new_df.sort_values(by='rank').reset_index(drop=True)

In [11]:
new_df

    rank                team group   rating
0      1              France     I  1877.32
1      2               Spain     H  1876.40
2      3           Argentina     J  1874.81
3      4             England     L  1825.97
4      5            Portugal     K  1763.83
5      6              Brazil     C  1761.16
6      7         Netherlands     F  1757.87
7      8             Morocco     C  1755.87
8      9             Belgium     G  1734.71
9     10             Germany     E  1730.37
10    11             Croatia     L  1717.07
11    13            Colombia     K  1693.09
12    14             Senegal     I  1688.99
13    15              Mexico     A  1681.03
14    16                 USA     D  1673.13
15    17             Uruguay     H  1673.07
16    18               Japan     F  1660.43
17    19         Switzerland     B  1649.40
18    22             Ecuador     E  1610.53
19    24         South Korea     A  1594.35
20    25              Turkey     D  1586.79
21    26           Australia     D  1581.22
22    27              Norway     I  1572.46
23    28             Austria     J  1568.91
24    29              Sweden     F  1551.34
25    30             Tunisia     F  1530.18
26    31                Iran     G  1521.43
27    32        Saudi Arabia     H  1510.87
28    33              Canada     B  1500.64
29    34            Scotland     C  1491.22
30    35             Algeria     J  1478.56
31    36             Czechia     A  1471.24
32    37         Ivory Coast     E  1461.83
33    38            Paraguay     D  1449.27
34    39               Egypt     G  1438.91
35    40        South Africa     A  1401.56
36    43  Bosnia-Herzegovina     B  1389.43
37    44               Ghana     L  1378.62
38    47              Panama     L  1361.44
39    48               Qatar     B  1340.21
40    51              Jordan     J  1271.38
41    52                Iraq     I  1258.73
42    55          Cape Verde     H  1241.56
43    58            Congo DR     K  1229.84
44    61          Uzbekistan     K  1198.43
45    72         New Zealand     G  1281.34
46    78               Haiti     C  1201.67
47    85             Curacao     E  1098.32

In [12]:
squad_metrics_map = {
    "France": {"avg_squad_age": 26.4, "avg_trans_value": 53.88},
    "Spain": {"avg_squad_age": 27.7, "avg_trans_value": 39.98},
    "Argentina": {"avg_squad_age": 28.3, "avg_trans_value": 34.14},
    "England": {"avg_squad_age": 25.8, "avg_trans_value": 52.30},
    "Portugal": {"avg_squad_age": 27.8, "avg_trans_value": 36.19},
    "Brazil": {"avg_squad_age": 27.7, "avg_trans_value": 28.00},
    "Netherlands": {"avg_squad_age": 27.2, "avg_trans_value": 32.75},
    "Morocco": {"avg_squad_age": 25.5, "avg_trans_value": 18.78},
    "Belgium": {"avg_squad_age": 27.2, "avg_trans_value": 20.36},
    "Germany": {"avg_squad_age": 27.3, "avg_trans_value": 35.85},
    "Croatia": {"avg_squad_age": 28.3, "avg_trans_value": 12.90},
    "Colombia": {"avg_squad_age": 27.6, "avg_trans_value": 9.03},
    "Senegal": {"avg_squad_age": 25.4, "avg_trans_value": 15.26},
    "Mexico": {"avg_squad_age": 26.1, "avg_trans_value": 5.11},
    "USA": {"avg_squad_age": 26.7, "avg_trans_value": 16.09},
    "Uruguay": {"avg_squad_age": 28.0, "avg_trans_value": 14.34},
    "Japan": {"avg_squad_age": 27.2, "avg_trans_value": 9.77},
    "Switzerland": {"avg_squad_age": 28.3, "avg_trans_value": 11.51},
    "Ecuador": {"avg_squad_age": 25.3, "avg_trans_value": 11.07},
    "South Korea": {"avg_squad_age": 27.7, "avg_trans_value": 5.16},
    "Turkiye": {"avg_squad_age": 26.2, "avg_trans_value": 15.51},
    "Australia": {"avg_squad_age": 26.9, "avg_trans_value": 2.00},
    "Norway": {"avg_squad_age": 26.9, "avg_trans_value": 20.83},
    "Austria": {"avg_squad_age": 27.6, "avg_trans_value": 8.90},
    "Sweden": {"avg_squad_age": 26.7, "avg_trans_value": 19.14},
    "Tunisia": {"avg_squad_age": 26.4, "avg_trans_value": 2.99},
    "Iran": {"avg_squad_age": 28.8, "avg_trans_value": 0.70},
    "Saudi Arabia": {"avg_squad_age": 27.5, "avg_trans_value": 0.95},
    "Canada": {"avg_squad_age": 26.4, "avg_trans_value": 7.22},
    "Scotland": {"avg_squad_age": 27.9, "avg_trans_value": 7.23},
    "Algeria": {"avg_squad_age": 25.4, "avg_trans_value": 12.25},
    "Czechia": {"avg_squad_age": 27.1, "avg_trans_value": 5.41},
    "Ivory Coast": {"avg_squad_age": 25.1, "avg_trans_value": 20.86},
    "Paraguay": {"avg_squad_age": 27.3, "avg_trans_value": 3.89},
    "Egypt": {"avg_squad_age": 27.8, "avg_trans_value": 5.48},
    "South Africa": {"avg_squad_age": 26.6, "avg_trans_value": 1.17},
    "Bosnia-Herzegovina": {"avg_squad_age": 26.7, "avg_trans_value": 4.35},
    "Ghana": {"avg_squad_age": 24.6, "avg_trans_value": 7.74},
    "Panama": {"avg_squad_age": 29.5, "avg_trans_value": 0.90},
    "Qatar": {"avg_squad_age": 28.4, "avg_trans_value": 0.47},
    "Jordan": {"avg_squad_age": 27.5, "avg_trans_value": 0.38},
    "Iraq": {"avg_squad_age": 25.6, "avg_trans_value": 0.68},
    "Cape Verde": {"avg_squad_age": 29.1, "avg_trans_value": 1.71},
    "DR Congo": {"avg_squad_age": 28.4, "avg_trans_value": 6.31},
    "Uzbekistan": {"avg_squad_age": 26.5, "avg_trans_value": 2.03},
    "New Zealand": {"avg_squad_age": 28.2, "avg_trans_value": 0.94},
    "Haiti": {"avg_squad_age": 27.2, "avg_trans_value": 2.18},
    "Curacao": {"avg_squad_age": 28.0, "avg_trans_value": 1.01},
}

In [13]:
m=pd.DataFrame(squad_metrics_map)

In [14]:
m

,France,Spain,Argentina,England,Portugal,Brazil,Netherlands,Morocco,Belgium,Germany,...,Panama,Qatar,Jordan,Iraq,Cape Verde,DR Congo,Uzbekistan,New Zealand,Haiti,Curacao
avg_squad_age,26.40,27.70,28.30,25.8,27.80,27.7,27.20,25.50,27.20,27.30,...,29.5,28.40,27.50,25.60,29.10,28.40,26.50,28.20,27.20,28.00
avg_trans_value,53.88,39.98,34.14,52.3,36.19,28.0,32.75,18.78,20.36,35.85,...,0.9,0.47,0.38,0.68,1.71,6.31,2.03,0.94,2.18,1.01

In [15]:
m=m.T

In [16]:
m

                    avg_squad_age  avg_trans_value
France                       26.4            53.88
Spain                        27.7            39.98
Argentina                    28.3            34.14
England                      25.8            52.30
Portugal                     27.8            36.19
Brazil                       27.7            28.00
Netherlands                  27.2            32.75
Morocco                      25.5            18.78
Belgium                      27.2            20.36
Germany                      27.3            35.85
Croatia                      28.3            12.90
Colombia                     27.6             9.03
Senegal                      25.4            15.26
Mexico                       26.1             5.11
USA                          26.7            16.09
Uruguay                      28.0            14.34
Japan                        27.2             9.77
Switzerland                  28.3            11.51
Ecuador                      25.3            11.07
South Korea                  27.7             5.16
Turkiye                      26.2            15.51
Australia                    26.9             2.00
Norway                       26.9            20.83
Austria                      27.6             8.90
Sweden                       26.7            19.14
Tunisia                      26.4             2.99
Iran                         28.8             0.70
Saudi Arabia                 27.5             0.95
Canada                       26.4             7.22
Scotland                     27.9             7.23
Algeria                      25.4            12.25
Czechia                      27.1             5.41
Ivory Coast                  25.1            20.86
Paraguay                     27.3             3.89
Egypt                        27.8             5.48
South Africa                 26.6             1.17
Bosnia-Herzegovina           26.7             4.35
Ghana                        24.6             7.74
Panama                       29.5             0.90
Qatar                        28.4             0.47
Jordan                       27.5             0.38
Iraq                         25.6             0.68
Cape Verde                   29.1             1.71
DR Congo                     28.4             6.31
Uzbekistan                   26.5             2.03
New Zealand                  28.2             0.94
Haiti                        27.2             2.18
Curacao                      28.0             1.01

In [17]:
# Align name variations to match my squad_metrics_map keys
new_df['team'] = new_df['team'].replace({
    'Turkey': 'Turkiye',
    'Congo DR': 'DR Congo'
})

In [18]:

new_df = new_df.merge(m[['avg_squad_age', 'avg_trans_value']], 
                      left_on='team', 
                      right_index=True, 
                      how='left')

In [19]:
new_df

    rank                team group   rating  avg_squad_age  avg_trans_value
0      1              France     I  1877.32           26.4            53.88
1      2               Spain     H  1876.40           27.7            39.98
2      3           Argentina     J  1874.81           28.3            34.14
3      4             England     L  1825.97           25.8            52.30
4      5            Portugal     K  1763.83           27.8            36.19
5      6              Brazil     C  1761.16           27.7            28.00
6      7         Netherlands     F  1757.87           27.2            32.75
7      8             Morocco     C  1755.87           25.5            18.78
8      9             Belgium     G  1734.71           27.2            20.36
9     10             Germany     E  1730.37           27.3            35.85
10    11             Croatia     L  1717.07           28.3            12.90
11    13            Colombia     K  1693.09           27.6             9.03
12    14             Senegal     I  1688.99           25.4            15.26
13    15              Mexico     A  1681.03           26.1             5.11
14    16                 USA     D  1673.13           26.7            16.09
15    17             Uruguay     H  1673.07           28.0            14.34
16    18               Japan     F  1660.43           27.2             9.77
17    19         Switzerland     B  1649.40           28.3            11.51
18    22             Ecuador     E  1610.53           25.3            11.07
19    24         South Korea     A  1594.35           27.7             5.16
20    25             Turkiye     D  1586.79           26.2            15.51
21    26           Australia     D  1581.22           26.9             2.00
22    27              Norway     I  1572.46           26.9            20.83
23    28             Austria     J  1568.91           27.6             8.90
24    29              Sweden     F  1551.34           26.7            19.14
25    30             Tunisia     F  1530.18           26.4             2.99
26    31                Iran     G  1521.43           28.8             0.70
27    32        Saudi Arabia     H  1510.87           27.5             0.95
28    33              Canada     B  1500.64           26.4             7.22
29    34            Scotland     C  1491.22           27.9             7.23
30    35             Algeria     J  1478.56           25.4            12.25
31    36             Czechia     A  1471.24           27.1             5.41
32    37         Ivory Coast     E  1461.83           25.1            20.86
33    38            Paraguay     D  1449.27           27.3             3.89
34    39               Egypt     G  1438.91           27.8             5.48
35    40        South Africa     A  1401.56           26.6             1.17
36    43  Bosnia-Herzegovina     B  1389.43           26.7             4.35
37    44               Ghana     L  1378.62           24.6             7.74
38    47              Panama     L  1361.44           29.5             0.90
39    48               Qatar     B  1340.21           28.4             0.47
40    51              Jordan     J  1271.38           27.5             0.38
41    52                Iraq     I  1258.73           25.6             0.68
42    55          Cape Verde     H  1241.56           29.1             1.71
43    58            DR Congo     K  1229.84           28.4             6.31
44    61          Uzbekistan     K  1198.43           26.5             2.03
45    72         New Zealand     G  1281.34           28.2             0.94
46    78               Haiti     C  1201.67           27.2             2.18
47    85             Curacao     E  1098.32           28.0             1.01

In [20]:
match=[{'W':4,'D':1,'L':0,'GF':14,'GA':5},
       {'W':3,'D':2,'L':0,'GF':13,'GA':2},
       {'W':5,'D':0,'L':0,'GF':16,'GA':1},
       {'W':3,'D':1,'L':1,'GF':10,'GA':2},
       {'W':2,'D':2,'L':1,'GF':13,'GA':5},
       {'W':3,'D':1,'L':1,'GF':13,'GA':6},
       {'W':3,'D':2,'L':0,'GF':12,'GA':3},
       {'W':3,'D':2,'L':0,'GF':8,'GA':2},
       {'W':3,'D':2,'L':0,'GF':18,'GA':6},
       {'W':5,'D':0,'L':0,'GF':18,'GA':4},
       {'W':4,'D':0,'L':1,'GF':12,'GA':7},
       {'W':2,'D':1,'L':2,'GF':7,'GA':6},
       {'W':3,'D':0,'L':2,'GF':8,'GA':7},
       {'W':3,'D':2,'L':0,'GF':8,'GA':1},
       {'W':3,'D':0,'L':2,'GF':12,'GA':11},
       {'W':1,'D':3,'L':1,'GF':4,'GA':7},
       {'W':5,'D':0,'L':0,'GF':8,'GA':0},
       {'W':2,'D':2,'L':1,'GF':12,'GA':7},
       {'W':2,'D':3,'L':0,'GF':6,'GA':3},
       {'W':3,'D':0,'L':2,'GF':8,'GA':5},
       {'W':4,'D':1,'L':0,'GF':10,'GA':3},
       {'W':2,'D':0,'L':3,'GF':6,'GA':6},
       {'W':2,'D':2,'L':1,'GF':10,'GA':5},
       {'W':3,'D':1,'L':1,'GF':9,'GA':3},
       {'W':2,'D':1,'L':2,'GF':8,'GA':9},
       {'W':1,'D':3,'L':1,'GF':5,'GA':5},
       {'W':2,'D':2,'L':1,'GF':6,'GA':2},
       {'W':0,'D':1,'L':4,'GF':2,'GA':9},
       {'W':2,'D':3,'L':0,'GF':5,'GA':2},
       {'W':2,'D':0,'L':3,'GF':10,'GA':7},
       {'W':3,'D':1,'L':1,'GF':11,'GA':3},
       {'W':3,'D':2,'L':0,'GF':13,'GA':5},
       {'W':4,'D':0,'L':1,'GF':13,'GA':4},
       {'W':2,'D':0,'L':3,'GF':5,'GA':7},
       {'W':2,'D':2,'L':1,'GF':5,'GA':1},
       {'W':1,'D':2,'L':2,'GF':6,'GA':7},
       {'W':1,'D':4,'L':0,'GF':6,'GA':4},
       {'W':0,'D':0,'L':5,'GF':2,'GA':11},
       {'W':1,'D':2,'L':2,'GF':6,'GA':10},
       {'W':0,'D':1,'L':4,'GF':3,'GA':8},
       {'W':2,'D':1,'L':2,'GF':7,'GA':9},
       {'W':3,'D':0,'L':2,'GF':5,'GA':5},
       {'W':1,'D':3,'L':1,'GF':7,'GA':6},
       {'W':3,'D':1,'L':1,'GF':7,'GA':2},
       {'W':2,'D':2,'L':1,'GF':6,'GA':3},
       {'W':1,'D':1,'L':3,'GF':6,'GA':8},
       {'W':2,'D':1,'L':2,'GF':4,'GA':5},
       {'W':1,'D':1,'L':3,'GF':9,'GA':11},
      ]

In [21]:

match_df = pd.DataFrame(match)
match_df['GD'] = match_df['GF'] - match_df['GA']
new_df[['W', 'D', 'L', 'GF', 'GA', 'GD']] = match_df[['W', 'D', 'L', 'GF', 'GA', 'GD']]
new_df

,rank,team,group,rating,avg_squad_age,avg_trans_value,W,D,L,GF,GA,GD
0,1,France,I,1877.32,26.4,53.88,4,1,0,14,5,9
1,2,Spain,H,1876.40,27.7,39.98,3,2,0,13,2,11
2,3,Argentina,J,1874.81,28.3,34.14,5,0,0,16,1,15
3,4,England,L,1825.97,25.8,52.30,3,1,1,10,2,8
4,5,Portugal,K,1763.83,27.8,36.19,2,2,1,13,5,8
5,6,Brazil,C,1761.16,27.7,28.00,3,1,1,13,6,7
6,7,Netherlands,F,1757.87,27.2,32.75,3,2,0,12,3,9
7,8,Morocco,C,1755.87,25.5,18.78,3,2,0,8,2,6
8,9,Belgium,G,1734.71,27.2,20.36,3,2,0,18,6,12
9,10,Germany,E,1730.37,27.3,35.85,5,0,0,18,4,14
10,11,Croatia,L,1717.07,28.3,12.90,4,0,1,12,7,5
11,13,Colombia,K,1693.09,27.6,9.03,2,1,2,7,6,1
12,14,Senegal,I,1688.99,25.4,15.26,3,0,2,8,7,1
13,15,Mexico,A,1681.03,26.1,5.11,3,2,0,8,1,7
14,16,USA,D,1673.13,26.7,16.09,3,0,2,12,11,1
15,17,Uruguay,H,1673.07,28.0,14.34,1,3,1,4,7,-3
16,18,Japan,F,1660.43,27.2,9.77,5,0,0,8,0,8
17,19,Switzerland,B,1649.40,28.3,11.51,2,2,1,12,7,5
18,22,Ecuador,E,1610.53,25.3,11.07,2,3,0,6,3,3
19,24,South Korea,A,1594.35,27.7,5.16,3,0,2,8,5,3
20,25,Turkiye,D,1586.79,26.2,15.51,4,1,0,10,3,7
21,26,Australia,D,1581.22,26.9,2.00,2,0,3,6,6,0
22,27,Norway,I,1572.46,26.9,20.83,2,2,1,10,5,5
23,28,Austria,J,1568.91,27.6,8.90,3,1,1,9,3,6
24,29,Sweden,F,1551.34,26.7,19.14,2,1,2,8,9,-1
25,30,Tunisia,F,1530.18,26.4,2.99,1,3,1,5,5,0
26,31,Iran,G,1521.43,28.8,0.70,2,2,1,6,2,4
27,32,Saudi Arabia,H,1510.87,27.5,0.95,0,1,4,2,9,-7
28,33,Canada,B,1500.64,26.4,7.22,2,3,0,5,2,3
29,34,Scotland,C,1491.22,27.9,7.23,2,0,3,10,7,3
30,35,Algeria,J,1478.56,25.4,12.25,3,1,1,11,3,8
31,36,Czechia,A,1471.24,27.1,5.41,3,2,0,13,5,8
32,37,Ivory Coast,E,1461.83,25.1,20.86,4,0,1,13,4,9
33,38,Paraguay,D,1449.27,27.3,3.89,2,0,3,5,7,-2
34,39,Egypt,G,1438.91,27.8,5.48,2,2,1,5,1,4
35,40,South Africa,A,1401.56,26.6,1.17,1,2,2,6,7,-1
36,43,Bosnia-Herzegovina,B,1389.43,26.7,4.35,1,4,0,6,4,2
37,44,Ghana,L,1378.62,24.6,7.74,0,0,5,2,11,-9
38,47,Panama,L,1361.44,29.5,0.90,1,2,2,6,10,-4
39,48,Qatar,B,1340.21,28.4,0.47,0,1,4,3,8,-5
40,51,Jordan,J,1271.38,27.5,0.38,2,1,2,7,9,-2
41,52,Iraq,I,1258.73,25.6,0.68,3,0,2,5,5,0
42,55,Cape Verde,H,1241.56,29.1,1.71,1,3,1,7,6,1
43,58,DR Congo,K,1229.84,28.4,6.31,3,1,1,7,2,5
44,61,Uzbekistan,K,1198.43,26.5,2.03,2,2,1,6,3,3
45,72,New Zealand,G,1281.34,28.2,0.94,1,1,3,6,8,-2
46,78,Haiti,C,1201.67,27.2,2.18,2,1,2,4,5,-1
47,85,Curacao,E,1098.32,28.0,1.01,1,1,3,9,11,-2

In [22]:
new_df.isnull().sum()

rank               0
team               0
group              0
rating             0
avg_squad_age      0
avg_trans_value    0
W                  0
D                  0
L                  0
GF                 0
GA                 0
GD                 0
dtype: int64

In [23]:
new_df['W%']=(new_df['W']/5)*100
new_df

,rank,team,group,rating,avg_squad_age,avg_trans_value,W,D,L,GF,GA,GD,W%
0,1,France,I,1877.32,26.4,53.88,4,1,0,14,5,9,80.0
1,2,Spain,H,1876.40,27.7,39.98,3,2,0,13,2,11,60.0
2,3,Argentina,J,1874.81,28.3,34.14,5,0,0,16,1,15,100.0
3,4,England,L,1825.97,25.8,52.30,3,1,1,10,2,8,60.0
4,5,Portugal,K,1763.83,27.8,36.19,2,2,1,13,5,8,40.0
5,6,Brazil,C,1761.16,27.7,28.00,3,1,1,13,6,7,60.0
6,7,Netherlands,F,1757.87,27.2,32.75,3,2,0,12,3,9,60.0
7,8,Morocco,C,1755.87,25.5,18.78,3,2,0,8,2,6,60.0
8,9,Belgium,G,1734.71,27.2,20.36,3,2,0,18,6,12,60.0
9,10,Germany,E,1730.37,27.3,35.85,5,0,0,18,4,14,100.0
10,11,Croatia,L,1717.07,28.3,12.90,4,0,1,12,7,5,80.0
11,13,Colombia,K,1693.09,27.6,9.03,2,1,2,7,6,1,40.0
12,14,Senegal,I,1688.99,25.4,15.26,3,0,2,8,7,1,60.0
13,15,Mexico,A,1681.03,26.1,5.11,3,2,0,8,1,7,60.0
14,16,USA,D,1673.13,26.7,16.09,3,0,2,12,11,1,60.0
15,17,Uruguay,H,1673.07,28.0,14.34,1,3,1,4,7,-3,20.0
16,18,Japan,F,1660.43,27.2,9.77,5,0,0,8,0,8,100.0
17,19,Switzerland,B,1649.40,28.3,11.51,2,2,1,12,7,5,40.0
18,22,Ecuador,E,1610.53,25.3,11.07,2,3,0,6,3,3,40.0
19,24,South Korea,A,1594.35,27.7,5.16,3,0,2,8,5,3,60.0
20,25,Turkiye,D,1586.79,26.2,15.51,4,1,0,10,3,7,80.0
21,26,Australia,D,1581.22,26.9,2.00,2,0,3,6,6,0,40.0
22,27,Norway,I,1572.46,26.9,20.83,2,2,1,10,5,5,40.0
23,28,Austria,J,1568.91,27.6,8.90,3,1,1,9,3,6,60.0
24,29,Sweden,F,1551.34,26.7,19.14,2,1,2,8,9,-1,40.0
25,30,Tunisia,F,1530.18,26.4,2.99,1,3,1,5,5,0,20.0
26,31,Iran,G,1521.43,28.8,0.70,2,2,1,6,2,4,40.0
27,32,Saudi Arabia,H,1510.87,27.5,0.95,0,1,4,2,9,-7,0.0
28,33,Canada,B,1500.64,26.4,7.22,2,3,0,5,2,3,40.0
29,34,Scotland,C,1491.22,27.9,7.23,2,0,3,10,7,3,40.0
30,35,Algeria,J,1478.56,25.4,12.25,3,1,1,11,3,8,60.0
31,36,Czechia,A,1471.24,27.1,5.41,3,2,0,13,5,8,60.0
32,37,Ivory Coast,E,1461.83,25.1,20.86,4,0,1,13,4,9,80.0
33,38,Paraguay,D,1449.27,27.3,3.89,2,0,3,5,7,-2,40.0
34,39,Egypt,G,1438.91,27.8,5.48,2,2,1,5,1,4,40.0
35,40,South Africa,A,1401.56,26.6,1.17,1,2,2,6,7,-1,20.0
36,43,Bosnia-Herzegovina,B,1389.43,26.7,4.35,1,4,0,6,4,2,20.0
37,44,Ghana,L,1378.62,24.6,7.74,0,0,5,2,11,-9,0.0
38,47,Panama,L,1361.44,29.5,0.90,1,2,2,6,10,-4,20.0
39,48,Qatar,B,1340.21,28.4,0.47,0,1,4,3,8,-5,0.0
40,51,Jordan,J,1271.38,27.5,0.38,2,1,2,7,9,-2,40.0
41,52,Iraq,I,1258.73,25.6,0.68,3,0,2,5,5,0,60.0
42,55,Cape Verde,H,1241.56,29.1,1.71,1,3,1,7,6,1,20.0
43,58,DR Congo,K,1229.84,28.4,6.31,3,1,1,7,2,5,60.0
44,61,Uzbekistan,K,1198.43,26.5,2.03,2,2,1,6,3,3,40.0
45,72,New Zealand,G,1281.34,28.2,0.94,1,1,3,6,8,-2,20.0
46,78,Haiti,C,1201.67,27.2,2.18,2,1,2,4,5,-1,40.0
47,85,Curacao,E,1098.32,28.0,1.01,1,1,3,9,11,-2,20.0

In [24]:
# Saving the DataFrame to a CSV file without the row index numbers
new_df.to_csv('world_cup_2026_teams_last_5_matches_data.csv', index=False)

In [25]:
def Rating_Difference(team1, team2):
    
    idx1 = new_df[new_df['team'] == team1].index[0]
    idx2 = new_df[new_df['team'] == team2].index[0]
    
    
    diff = new_df.loc[idx1, 'rating'] - new_df.loc[idx2, 'rating']
    return diff

In [26]:
new_df[new_df['team']=='Senegal'].index[0]

np.int64(12)

In [27]:
'Senegal' in new_df['team'].values

True

In [28]:
Rating_Difference('France', 'Senegal')

np.float64(188.32999999999993)

In [29]:
def value_difference(team1,team2):
    idx1 = new_df[new_df['team'] == team1].index[0]
    idx2 = new_df[new_df['team'] == team2].index[0]
    diff = new_df.loc[idx1, 'avg_trans_value'] - new_df.loc[idx2, 'avg_trans_value']
    return diff

In [30]:
value_difference('France', 'Senegal')

np.float64(38.620000000000005)

In [31]:
def form_diff(team1,team2):
    idx1 = new_df[new_df['team'] == team1].index[0]
    idx2 = new_df[new_df['team'] == team2].index[0]
    diff = new_df.loc[idx1, 'W%'] - new_df.loc[idx2, 'W%']
    return diff

In [32]:
form_diff('France', 'Senegal')

np.float64(20.0)

In [33]:
training_fixtures = [
    {
        "t1": "France",
        "t2": "Colombia",
        "label": 2,
        "gd": 2,
        "gf": 3,
        "ga": 1
    },
    {
        "t1": "France",
        "t2": "Brazil",
        "label": 2,
        "gd": 1,
        "gf": 2,
        "ga": 1
    },
    {
        "t1": "Spain",
        "t2": "Netherlands",
        "label": 1,
        "gd": 0,
        "gf": 3,
        "ga": 3
    },
    {
        "t1": "Spain",
        "t2": "Portugal",
        "label": 1,
        "gd": 0,
        "gf": 2,
        "ga": 2
    },
    {
        "t1": "Spain",
        "t2": "France",
        "label": 2,
        "gd": 1,
        "gf": 5,
        "ga": 4
    },
    {
        "t1": "Argentina",
        "t2": "Brazil",
        "label": 2,
        "gd": 3,
        "gf": 4,
        "ga": 1
    },
    {
        "t1": "Argentina",
        "t2": "Colombia",
        "label": 1,
        "gd": 0,
        "gf": 1,
        "ga": 1
    },
    {
        "t1": "Argentina",
        "t2": "Ecuador",
        "label": 0,
        "gd": -1,
        "gf": 0,
        "ga": 1
    },
    {
        "t1": "England",
        "t2": "Japan",
        "label": 0,
        "gd": -1,
        "gf": 0,
        "ga": 1
    },
    {
        "t1": "England",
        "t2": "Uruguay",
        "label": 1,
        "gd": 0,
        "gf": 1,
        "ga": 1
    },
    {
        "t1": "England",
        "t2": "Netherlands",
        "label": 1,
        "gd": 0,
        "gf": 1,
        "ga": 1
    },
    {
        "t1": "England",
        "t2": "Spain",
        "label": 0,
        "gd": -1,
        "gf": 1,
        "ga": 2
    },
    {
        "t1": "Portugal",
        "t2": "USA",
        "label": 2,
        "gd": 2,
        "gf": 2,
        "ga": 0
    },
    {
        "t1": "Portugal",
        "t2": "Mexico",
        "label": 1,
        "gd": 0,
        "gf": 0,
        "ga": 0
    },
    {
        "t1": "Portugal",
        "t2": "Germany",
        "label": 2,
        "gd": 1,
        "gf": 2,
        "ga": 1
    },
    {
        "t1": "Portugal",
        "t2": "Spain",
        "label": 1,
        "gd": 0,
        "gf": 2,
        "ga": 2
    },
    {
        "t1": "Brazil",
        "t2": "France",
        "label": 0,
        "gd": -1,
        "gf": 1,
        "ga": 2
    },
    {
        "t1": "Brazil",
        "t2": "Croatia",
        "label": 2,
        "gd": 2,
        "gf": 3,
        "ga": 1
    },
    {
        "t1": "Brazil",
        "t2": "Panama",
        "label": 2,
        "gd": 4,
        "gf": 6,
        "ga": 2
    },
    {
        "t1": "Brazil",
        "t2": "Senegal",
        "label": 2,
        "gd": 2,
        "gf": 2,
        "ga": 0
    },
    {
        "t1": "Brazil",
        "t2": "Tunisia",
        "label": 1,
        "gd": 0,
        "gf": 1,
        "ga": 1
    },
    {
        "t1": "Netherlands",
        "t2": "Norway",
        "label": 2,
        "gd": 1,
        "gf": 2,
        "ga": 1
    },
    {
        "t1": "Netherlands",
        "t2": "Ecuador",
        "label": 1,
        "gd": 0,
        "gf": 1,
        "ga": 1
    },
    {
        "t1": "Egypt",
        "t2": "Saudi Arabia",
        "label": 2,
        "gd": 4,
        "gf": 4,
        "ga": 0
    },
    {
        "t1": "Egypt",
        "t2": "Jordan",
        "label": 0,
        "gd": -3,
        "gf": 0,
        "ga": 3
    },
    {
        "t1": "Egypt",
        "t2": "Senegal",
        "label": 0,
        "gd": -1,
        "gf": 0,
        "ga": 1
    },
    {
        "t1": "Egypt",
        "t2": "Ivory Coast",
        "label": 2,
        "gd": 1,
        "gf": 3,
        "ga": 2
    },
    {
        "t1": "Haiti",
        "t2": "Saudi Arabia",
        "label": 0,
        "gd": -1,
        "gf": 0,
        "ga": 1
    },
    {
        "t1": "Haiti",
        "t2": "USA",
        "label": 0,
        "gd": -1,
        "gf": 1,
        "ga": 2
    },
    {
        "t1": "Haiti",
        "t2": "Tunisia",
        "label": 0,
        "gd": -1,
        "gf": 0,
        "ga": 1
    }
]

In [34]:

X_list = []
y_list = []


for match in training_fixtures:
    
    t1 = match['t1']
    t2 = match['t2']
    
 
    match_features = {
        'rating_diff': Rating_Difference(t1, t2),
        'value_diff': value_difference(t1, t2),
        'form_diff': form_diff(t1, t2)
    }
    X_list.append(match_features)
    
    
    match_targets = {
        'match_label': match.get('label'), # 2 = t1 win, 1 = draw, 0 = t2 win
        'match_gd': match.get('gd'),       # goal difference of that game
        'match_gf': match.get('gf'),       # Goals scored by t1
        'match_ga': match.get('ga')        # Goals scored by t2
    }
    y_list.append(match_targets)


X_train = pd.DataFrame(X_list)
y_train = pd.DataFrame(y_list)


X_train

    rating_diff  value_diff  form_diff
0        184.23       44.85       40.0
1        116.16       25.88       20.0
2        118.53        7.23        0.0
3        112.57        3.79       20.0
4         -0.92      -13.90      -20.0
5        113.65        6.14       40.0
6        181.72       25.11       60.0
7        264.28       23.07       60.0
8        165.54       42.53      -40.0
9        152.90       37.96       40.0
10        68.10       19.55        0.0
11       -50.43       12.32        0.0
12        90.70       20.10      -20.0
13        82.80       31.08      -20.0
14        33.46        0.34      -60.0
15      -112.57       -3.79      -20.0
16      -116.16      -25.88      -20.0
17        44.09       15.10      -20.0
18       399.72       27.10       40.0
19        72.17       12.74        0.0
20       230.98       25.01       40.0
21       185.41       11.92       20.0
22       147.34       21.68       20.0
23       -71.96        4.53       40.0
24       167.53        5.10        0.0
25      -250.08       -9.78      -20.0
26       -22.92      -15.38      -40.0
27      -309.20        1.23       40.0
28      -471.46      -13.91      -20.0
29      -328.51       -0.81       20.0

In [35]:
def age_diff(team1,team2):
    idx1 = new_df[new_df['team'] == team1].index[0]
    idx2 = new_df[new_df['team'] == team2].index[0]
    
    
    diff = new_df.loc[idx1, 'avg_squad_age'] - new_df.loc[idx2, 'avg_squad_age']
    return diff

In [36]:
age_diff('France', 'Senegal')

np.float64(1.0)

In [37]:
def defense_stability_diff(team1, team2):
    idx1 = new_df[new_df['team'] == team1].index[0]
    idx2 = new_df[new_df['team'] == team2].index[0]
    
    # Calculate average goals conceded per match over the last 5 games
    avg_ga_t1 = new_df.loc[idx1, 'GA'] / 5
    avg_ga_t2 = new_df.loc[idx2, 'GA'] / 5
    
    # A negative difference means Team 1 concedes FEWER goals than Team 2 (better defense)
    return avg_ga_t1 - avg_ga_t2

In [38]:
defense_stability_diff('France', 'Senegal')

np.float64(-0.3999999999999999)

In [39]:
X_list = []
y_list = []

for match in training_fixtures:
    t1 = match['t1']
    t2 = match['t2']
    
    
    match_features = {
        'rating_diff': Rating_Difference(t1, t2),
        'value_diff': value_difference(t1, t2),
        'form_diff': form_diff(t1, t2),
        'age_diff': age_diff(t1, t2),
        'def_stability_diff': defense_stability_diff(t1, t2) 
    }
    X_list.append(match_features)
    
    match_targets = {
        'match_label': match.get('label'), 
        'match_gd': match.get('gd'),       
        'match_gf': match.get('gf'),       
        'match_ga': match.get('ga')        
    }
    y_list.append(match_targets)

X_train = pd.DataFrame(X_list)
y_train = pd.DataFrame(y_list)


X_train

    rating_diff  value_diff  form_diff  age_diff  def_stability_diff
0        184.23       44.85       40.0      -1.2                -0.2
1        116.16       25.88       20.0      -1.3                -0.2
2        118.53        7.23        0.0       0.5                -0.2
3        112.57        3.79       20.0      -0.1                -0.6
4         -0.92      -13.90      -20.0       1.3                -0.6
5        113.65        6.14       40.0       0.6                -1.0
6        181.72       25.11       60.0       0.7                -1.0
7        264.28       23.07       60.0       3.0                -0.4
8        165.54       42.53      -40.0      -1.4                 0.4
9        152.90       37.96       40.0      -2.2                -1.0
10        68.10       19.55        0.0      -1.4                -0.2
11       -50.43       12.32        0.0      -1.9                 0.0
12        90.70       20.10      -20.0       1.1                -1.2
13        82.80       31.08      -20.0       1.7                 0.8
14        33.46        0.34      -60.0       0.5                 0.2
15      -112.57       -3.79      -20.0       0.1                 0.6
16      -116.16      -25.88      -20.0       1.3                 0.2
17        44.09       15.10      -20.0      -0.6                -0.2
18       399.72       27.10       40.0      -1.8                -0.8
19        72.17       12.74        0.0       2.3                -0.2
20       230.98       25.01       40.0       1.3                 0.2
21       185.41       11.92       20.0       0.3                -0.4
22       147.34       21.68       20.0       1.9                 0.0
23       -71.96        4.53       40.0       0.3                -1.6
24       167.53        5.10        0.0       0.3                -1.6
25      -250.08       -9.78      -20.0       2.4                -1.2
26       -22.92      -15.38      -40.0       2.7                -0.6
27      -309.20        1.23       40.0      -0.3                -0.8
28      -471.46      -13.91      -20.0       0.5                -1.2
29      -328.51       -0.81       20.0       0.8                 0.0

In [40]:
y_train

    match_label  match_gd  match_gf  match_ga
0             2         2         3         1
1             2         1         2         1
2             1         0         3         3
3             1         0         2         2
4             2         1         5         4
5             2         3         4         1
6             1         0         1         1
7             0        -1         0         1
8             0        -1         0         1
9             1         0         1         1
10            1         0         1         1
11            0        -1         1         2
12            2         2         2         0
13            1         0         0         0
14            2         1         2         1
15            1         0         2         2
16            0        -1         1         2
17            2         2         3         1
18            2         4         6         2
19            2         2         2         0
20            1         0         1         1
21            2         1         2         1
22            1         0         1         1
23            2         4         4         0
24            0        -3         0         3
25            0        -1         0         1
26            2         1         3         2
27            0        -1         0         1
28            0        -1         1         2
29            0        -1         0         1

In [41]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV


rf_base = RandomForestClassifier(random_state=42)


param_grid = {
    'n_estimators': [10, 30, 50],       # Number of trees in the forest
    'max_depth': [3, 4, 5, None],       # Limit tree depth to prevent memorization
    'min_samples_split': [2, 5],        # Minimum samples required to split a node
    'max_features': ['sqrt', 'log2']    # Number of features considered at each split
}

# 3. Using up Grid Search 
# (cv=3 means it will split your 30 rows into three 10-row chunks to validate)
grid_search = GridSearchCV(
    estimator=rf_base, 
    param_grid=param_grid, 
    cv=3, 
    scoring='accuracy', 
    n_jobs=-1
)


y_label = y_train['match_label']
grid_search.fit(X_train, y_label)


print("Best Parameters Found:")
print(grid_search.best_params_)
print(f"\n Best Cross-Validation Accuracy: {grid_search.best_score_*100:.1f}%")


best_rf_model = grid_search.best_estimator_

Best Parameters Found:
{'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 2, 'n_estimators': 30}

 Best Cross-Validation Accuracy: 46.7%

In [42]:
def predict_match_percentages(team1, team2):
   
    match_features = pd.DataFrame([{
        'rating_diff': Rating_Difference(team1, team2),
        'value_diff': value_difference(team1, team2),
        'form_diff': form_diff(team1, team2),
        'age_diff': age_diff(team1, team2),
        'def_stability_diff': defense_stability_diff(team1, team2)
    }])
    
   
    probabilities = grid_search.predict_proba(match_features)[0]
    
    
    t2_win_pct = probabilities[0] * 100
    draw_pct = probabilities[1] * 100
    t1_win_pct = probabilities[2] * 100
    
    print(f" 2026 World Cup Match Simulation: {team1} vs {team2}")
    print("=" * 50)
    print(f" {team1} Win Probability: {t1_win_pct:.1f}%")
    print(f" Draw Probability: {draw_pct:.1f}%")
    print(f" {team2} Win Probability: {t2_win_pct:.1f}%")

In [43]:
predict_match_percentages("France", "Argentina")

 2026 World Cup Match Simulation: France vs Argentina
==================================================
 France Win Probability: 17.7%
 Draw Probability: 56.3%
 Argentina Win Probability: 26.0%

In [44]:
match_results=pd.read_csv('Match_Results.csv')#got it from kaggle

In [45]:
match_results

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,False
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,False
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
47394,2024-07-10,Netherlands,England,1,2,UEFA Euro,Dortmund,Germany,True
47395,2024-07-10,Uruguay,Colombia,0,1,Copa América,Charlotte,United States,True
47396,2024-07-13,Canada,Uruguay,2,2,Copa América,Charlotte,United States,True
47397,2024-07-14,Spain,England,2,1,UEFA Euro,Berlin,Germany,True
47398,2024-07-14,Argentina,Colombia,1,0,Copa América,Miami Gardens,United States,True

In [46]:
match_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47399 entries, 0 to 47398
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        47399 non-null  object
 1   home_team   47399 non-null  object
 2   away_team   47399 non-null  object
 3   home_score  47399 non-null  int64
 4   away_score  47399 non-null  int64
 5   tournament  47399 non-null  object
 6   city        47399 non-null  object
 7   country     47399 non-null  object
 8   neutral     47399 non-null  bool
dtypes: bool(1), int64(2), object(6)
memory usage: 2.9+ MB

In [47]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rank             48 non-null     int64
 1   team             48 non-null     object
 2   group            48 non-null     object
 3   rating           48 non-null     float64
 4   avg_squad_age    48 non-null     float64
 5   avg_trans_value  48 non-null     float64
 6   W                48 non-null     int64
 7   D                48 non-null     int64
 8   L                48 non-null     int64
 9   GF               48 non-null     int64
 10  GA               48 non-null     int64
 11  GD               48 non-null     int64
 12  W%               48 non-null     float64
dtypes: float64(4), int64(7), object(2)
memory usage: 5.0+ KB

In [48]:
match_results['date'] = pd.to_datetime(match_results['date'])

In [49]:
match_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47399 entries, 0 to 47398
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        47399 non-null  datetime64[ns]
 1   home_team   47399 non-null  object
 2   away_team   47399 non-null  object
 3   home_score  47399 non-null  int64
 4   away_score  47399 non-null  int64
 5   tournament  47399 non-null  object
 6   city        47399 non-null  object
 7   country     47399 non-null  object
 8   neutral     47399 non-null  bool
dtypes: bool(1), datetime64[ns](1), int64(2), object(5)
memory usage: 2.9+ MB

In [50]:
world_cup_teams=new_df['team'].values

In [51]:
world_cup_teams

array(['France', 'Spain', 'Argentina', 'England', 'Portugal', 'Brazil',
       'Netherlands', 'Morocco', 'Belgium', 'Germany', 'Croatia',
       'Colombia', 'Senegal', 'Mexico', 'USA', 'Uruguay', 'Japan',
       'Switzerland', 'Ecuador', 'South Korea', 'Turkiye', 'Australia',
       'Norway', 'Austria', 'Sweden', 'Tunisia', 'Iran', 'Saudi Arabia',
       'Canada', 'Scotland', 'Algeria', 'Czechia', 'Ivory Coast',
       'Paraguay', 'Egypt', 'South Africa', 'Bosnia-Herzegovina', 'Ghana',
       'Panama', 'Qatar', 'Jordan', 'Iraq', 'Cape Verde', 'DR Congo',
       'Uzbekistan', 'New Zealand', 'Haiti', 'Curacao'], dtype=object)

In [52]:
filtered_matches = match_results[
    (match_results['date'] >= '2018-01-01') & 
    (match_results['date'] <= '2024-12-31') & 
    (match_results['home_team'].isin(world_cup_teams)) & 
    (match_results['away_team'].isin(world_cup_teams))
].reset_index(drop=True)

In [53]:
filtered_matches

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,2018-02-28,Iraq,Saudi Arabia,4,1,Friendly,Basra,Iraq,False
1,2018-03-21,Iraq,Qatar,2,3,Friendly,Basra,Iraq,False
2,2018-03-23,France,Colombia,2,3,Friendly,Saint-Denis,France,False
3,2018-03-23,Germany,Spain,1,1,Friendly,Düsseldorf,Germany,False
4,2018-03-23,Netherlands,England,0,1,Friendly,Amsterdam,Netherlands,False
...,...,...,...,...,...,...,...,...,...
657,2024-07-10,Netherlands,England,1,2,UEFA Euro,Dortmund,Germany,True
658,2024-07-10,Uruguay,Colombia,0,1,Copa América,Charlotte,United States,True
659,2024-07-13,Canada,Uruguay,2,2,Copa América,Charlotte,United States,True
660,2024-07-14,Spain,England,2,1,UEFA Euro,Berlin,Germany,True
661,2024-07-14,Argentina,Colombia,1,0,Copa América,Miami Gardens,United States,True

In [54]:

filtered_matches = filtered_matches.drop(columns=['date'])


filtered_matches = filtered_matches.rename(columns={
    'home_team': 't1',
    'away_team': 't2',
    'home_score': 'gf',  # Goals scored by Team 1
    'away_score': 'ga'   # Goals scored by Team 2
})


filtered_matches['gd'] = filtered_matches['gf'] - filtered_matches['ga']


conditions = [
    (filtered_matches['gd'] > 0),  # T1 Wins
    (filtered_matches['gd'] == 0), # Draw
    (filtered_matches['gd'] < 0)   # T2 Wins
]
choices = [2, 1, 0]

filtered_matches['label'] = np.select(conditions, choices)


filtered_matches.head()

,t1,t2,gf,ga,tournament,city,country,neutral,gd,label
0,Iraq,Saudi Arabia,4,1,Friendly,Basra,Iraq,False,3,2
1,Iraq,Qatar,2,3,Friendly,Basra,Iraq,False,-1,0
2,France,Colombia,2,3,Friendly,Saint-Denis,France,False,-1,0
3,Germany,Spain,1,1,Friendly,Düsseldorf,Germany,False,0,1
4,Netherlands,England,0,1,Friendly,Amsterdam,Netherlands,False,-1,0

In [55]:
filtered_matches=filtered_matches.drop(columns=['city','country','neutral','tournament'])

In [56]:
filtered_matches.sample(4)

          t1          t2  gf  ga  gd  label
401    Spain    Portugal   1   1   0      1
239   France    Portugal   0   0   0      1
16   Morocco  Uzbekistan   2   0   2      2
581  Austria     Germany   2   0   2      2

In [57]:
filtered_matches.shape

(662, 6)

In [58]:
X_list = []
y_list = []


# Loop through my new large historical dataframe row by row
for idx, row in filtered_matches.iterrows():
    t1 = row['t1']
    t2 = row['t2']
    
    
    match_features = {
        'rating_diff': Rating_Difference(t1, t2),
        'value_diff': value_difference(t1, t2),
        'form_diff': form_diff(t1, t2),
        'age_diff': age_diff(t1, t2),
        'def_stability_diff': defense_stability_diff(t1, t2)
    }
    X_list.append(match_features)
    
    # label (2 = T1 Win, 1 = Draw, 0 = T2 Win)
    y_list.append(row['label'])

# Convert to clean final training DataFrames
X_train_large = pd.DataFrame(X_list)
y_train_large = np.array(y_list)

print(f" Generated X_train_large with shape: {X_train_large.shape}")
X_train_large.head()

 Generated X_train_large with shape: (662, 5)

   rating_diff  value_diff  form_diff  age_diff  def_stability_diff
0      -252.14       -0.27       60.0      -1.9                -0.8
1       -81.48        0.21       60.0      -2.8                -0.6
2       184.23       44.85       40.0      -1.2                -0.2
3      -146.03       -4.13       40.0      -0.4                 0.4
4       -68.10      -19.55        0.0       1.4                 0.2

In [59]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV


rf_base = RandomForestClassifier(random_state=42)


param_grid = {
    'n_estimators': [50, 100, 150],     
    'max_depth': [4, 6, 8, None],       
    'min_samples_split': [2, 5, 10],    
    'max_features': ['sqrt', 'log2']
}

# Using Grid Search with 5-Fold Cross-Validation 

grid_search_large = GridSearchCV(
    estimator=rf_base, 
    param_grid=param_grid, 
    cv=5, 
    scoring='accuracy', 
    n_jobs=-1
)


grid_search_large.fit(X_train_large, y_train_large)


print(" Upgraded Best Parameters Found:")
print(grid_search_large.best_params_)
print(f"\n Brand New Cross-Validation Accuracy: {grid_search_large.best_score_ * 100:.1f}%")

# 6. Save your new master model
best_rf_model_large = grid_search_large.best_estimator_

 Upgraded Best Parameters Found:
{'max_depth': 4, 'max_features': 'sqrt', 'min_samples_split': 10, 'n_estimators': 100}

 Brand New Cross-Validation Accuracy: 50.6%

In [60]:
# lets try regression rather than classification, and will calculate win probability on the basis of goal difference
# i am switching to regression because the accuracy isn't good enough

In [61]:
y_train_gd = filtered_matches['gd'].values

In [62]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV


rf_regressor = RandomForestRegressor(random_state=42)


param_grid_reg = {
    'n_estimators': [50, 100, 150],
    'max_depth': [4, 6, 8, None],
    'min_samples_split': [5, 10, 15],
    'max_features': ['sqrt', 'log2']
}


grid_search_reg = GridSearchCV(
    estimator=rf_regressor, 
    param_grid=param_grid_reg, 
    cv=5, 
    scoring='neg_mean_absolute_error', # will use negative mean absolute error
    n_jobs=-1
)


grid_search_reg.fit(X_train_large, y_train_gd)


print(" Best Regressor Parameters Found:")
print(grid_search_reg.best_params_)

# Calculating the actual Mean Absolute Error (MAE) by flipping the negative sign
mae = -grid_search_reg.best_score_
mae=round(mae, 2)
print("Average Cross-Validation Error:", mae, "goals")


best_rf_regressor = grid_search_reg.best_estimator_

 Best Regressor Parameters Found:
{'max_depth': 4, 'max_features': 'sqrt', 'min_samples_split': 10, 'n_estimators': 100}
Average Cross-Validation Error: 1.22 goals

In [63]:
def predict_full_match_analytics(team1, team2):

    match_features = pd.DataFrame([{
        'rating_diff': Rating_Difference(team1, team2),
        'value_diff': value_difference(team1, team2),
        'form_diff': form_diff(team1, team2),
        'age_diff': age_diff(team1, team2),
        'def_stability_diff': defense_stability_diff(team1, team2)
    }])
    
    
    base_gd = best_rf_regressor.predict(match_features)[0]
    
    # 3. Simulating the match 1,000 times for the percentages
    t1_wins = 0
    draws = 0
    t2_wins = 0
    simulations = 1000
    
    for _ in range(simulations):
        simulated_gd = np.random.normal(loc=base_gd, scale=1.22) #This takes that exact base_gd anchor point and shakes it up with match-day randomness using your 1.22 MAE score. This creates the realistic win/loss/draw percentages.
        if simulated_gd > 0.25:
            t1_wins += 1
        elif simulated_gd < -0.25:
            t2_wins += 1
        else:
            draws += 1
            
    t1_pct = (t1_wins / simulations) * 100
    draw_pct = (draws / simulations) * 100
    t2_pct = (t2_wins / simulations) * 100
    
    # Generating a realistic exact scoreline using a baseline average of 2.5 goals per game
    # I split the baseline goals using the predicted goal difference
    avg_total_goals = 2.5
    t1_expected_goals = max(0.2, (avg_total_goals + base_gd) / 2)
    t2_expected_goals = max(0.2, (avg_total_goals - base_gd) / 2)
    
    # Sample actual integer goals using the Poisson distribution
    t1_score = np.random.poisson(lam=t1_expected_goals)
    t2_score = np.random.poisson(lam=t2_expected_goals)
    
    
    print("Matchup:", team1, "vs", team2)
    print("---------------------------------")
    print(team1, "Win Probability:", round(t1_pct, 1), "%")
    print("Draw Probability:", round(draw_pct, 1), "%")
    print(team2, "Win Probability:", round(t2_pct, 1), "%")
    print("---------------------------------")
    print("Simulated Scoreline:", team1, t1_score, "-", t2_score, team2)

In [64]:
# Let x= expected goal for T1,y for T2
# therefore, x+y=2.5 and x-y=base_gd
# hence, (x+y)+(x-y)=2.5+base_gd
# x=(2.5+base_gd)/2
#y=(2.5-base_gd)/2

In [65]:
predict_full_match_analytics("France", "Colombia")

Matchup: France vs Colombia
---------------------------------
France Win Probability: 73.7 %
Draw Probability: 12.0 %
Colombia Win Probability: 14.3 %
---------------------------------
Simulated Scoreline: France 4 - 0 Colombia

In [66]:
print("🔍 Testing Model Against Independent Training Fixtures")
print("==================================================")

# Loop through your 30 holdout matches
for i, match in enumerate(training_fixtures):
    t1 = match['t1']
    t2 = match['t2']
    true_gf = match['gf']
    true_ga = match['ga']
    
    print(f"\nMatch #{i+1}: {t1} vs {t2}")
    print(f"Actual Result: {t1} {true_gf} - {true_ga} {t2}")
    
    # Run your full analytics function for this pair
    predict_full_match_analytics(t1, t2)
    print("-" * 40)

🔍 Testing Model Against Independent Training Fixtures
==================================================

Match #1: France vs Colombia
Actual Result: France 3 - 1 Colombia
Matchup: France vs Colombia
---------------------------------
France Win Probability: 73.9 %
Draw Probability: 9.4 %
Colombia Win Probability: 16.7 %
---------------------------------
Simulated Scoreline: France 2 - 2 Colombia
----------------------------------------

Match #2: France vs Brazil
Actual Result: France 2 - 1 Brazil
Matchup: France vs Brazil
---------------------------------
France Win Probability: 76.7 %
Draw Probability: 9.9 %
Brazil Win Probability: 13.4 %
---------------------------------
Simulated Scoreline: France 3 - 2 Brazil
----------------------------------------

Match #3: Spain vs Netherlands
Actual Result: Spain 3 - 3 Netherlands
Matchup: Spain vs Netherlands
---------------------------------
Spain Win Probability: 71.4 %
Draw Probability: 11.0 %
Netherlands Win Probability: 17.6 %
---------------------------------
Simulated Scoreline: Spain 2 - 1 Netherlands
----------------------------------------

Match #4: Spain vs Portugal
Actual Result: Spain 2 - 2 Portugal
Matchup: Spain vs Portugal
---------------------------------
Spain Win Probability: 58.9 %
Draw Probability: 15.5 %
Portugal Win Probability: 25.6 %
---------------------------------
Simulated Scoreline: Spain 2 - 0 Portugal
----------------------------------------

Match #5: Spain vs France
Actual Result: Spain 5 - 4 France
Matchup: Spain vs France
---------------------------------
Spain Win Probability: 40.3 %
Draw Probability: 14.4 %
France Win Probability: 45.3 %
---------------------------------
Simulated Scoreline: Spain 1 - 0 France
----------------------------------------

Match #6: Argentina vs Brazil
Actual Result: Argentina 4 - 1 Brazil
Matchup: Argentina vs Brazil
---------------------------------
Argentina Win Probability: 64.5 %
Draw Probability: 13.2 %
Brazil Win Probability: 22.3 %
---------------------------------
Simulated Scoreline: Argentina 2 - 1 Brazil
----------------------------------------

Match #7: Argentina vs Colombia
Actual Result: Argentina 1 - 1 Colombia
Matchup: Argentina vs Colombia
---------------------------------
Argentina Win Probability: 73.0 %
Draw Probability: 11.4 %
Colombia Win Probability: 15.6 %
---------------------------------
Simulated Scoreline: Argentina 1 - 1 Colombia
----------------------------------------

Match #8: Argentina vs Ecuador
Actual Result: Argentina 0 - 1 Ecuador
Matchup: Argentina vs Ecuador
---------------------------------
Argentina Win Probability: 81.8 %
Draw Probability: 8.3 %
Ecuador Win Probability: 9.9 %
---------------------------------
Simulated Scoreline: Argentina 2 - 1 Ecuador
----------------------------------------

Match #9: England vs Japan
Actual Result: England 0 - 1 Japan
Matchup: England vs Japan
---------------------------------
England Win Probability: 77.6 %
Draw Probability: 11.1 %
Japan Win Probability: 11.3 %
---------------------------------
Simulated Scoreline: England 4 - 1 Japan
----------------------------------------

Match #10: England vs Uruguay
Actual Result: England 1 - 1 Uruguay
Matchup: England vs Uruguay
---------------------------------
England Win Probability: 73.9 %
Draw Probability: 10.6 %
Uruguay Win Probability: 15.5 %
---------------------------------
Simulated Scoreline: England 2 - 0 Uruguay
----------------------------------------

Match #11: England vs Netherlands
Actual Result: England 1 - 1 Netherlands
Matchup: England vs Netherlands
---------------------------------
England Win Probability: 59.9 %
Draw Probability: 14.2 %
Netherlands Win Probability: 25.9 %
---------------------------------
Simulated Scoreline: England 2 - 0 Netherlands
----------------------------------------

Match #12: England vs Spain
Actual Result: England 1 - 2 Spain
Matchup: England vs Spain
---------------------------------
England Win Probability: 49.8 %
Draw Probability: 14.0 %
Spain Win Probability: 36.2 %
---------------------------------
Simulated Scoreline: England 0 - 1 Spain
----------------------------------------

Match #13: Portugal vs USA
Actual Result: Portugal 2 - 0 USA
Matchup: Portugal vs USA
---------------------------------
Portugal Win Probability: 73.4 %
Draw Probability: 10.0 %
USA Win Probability: 16.6 %
---------------------------------
Simulated Scoreline: Portugal 1 - 0 USA
----------------------------------------

Match #14: Portugal vs Mexico
Actual Result: Portugal 0 - 0 Mexico
Matchup: Portugal vs Mexico
---------------------------------
Portugal Win Probability: 74.7 %
Draw Probability: 10.7 %
Mexico Win Probability: 14.6 %
---------------------------------
Simulated Scoreline: Portugal 0 - 0 Mexico
----------------------------------------

Match #15: Portugal vs Germany
Actual Result: Portugal 2 - 1 Germany
Matchup: Portugal vs Germany
---------------------------------
Portugal Win Probability: 49.2 %
Draw Probability: 17.0 %
Germany Win Probability: 33.8 %
---------------------------------
Simulated Scoreline: Portugal 3 - 1 Germany
----------------------------------------

Match #16: Portugal vs Spain
Actual Result: Portugal 2 - 2 Spain
Matchup: Portugal vs Spain
---------------------------------
Portugal Win Probability: 37.6 %
Draw Probability: 14.7 %
Spain Win Probability: 47.7 %
---------------------------------
Simulated Scoreline: Portugal 1 - 1 Spain
----------------------------------------

Match #17: Brazil vs France
Actual Result: Brazil 1 - 2 France
Matchup: Brazil vs France
---------------------------------
Brazil Win Probability: 40.5 %
Draw Probability: 16.4 %
France Win Probability: 43.1 %
---------------------------------
Simulated Scoreline: Brazil 0 - 4 France
----------------------------------------

Match #18: Brazil vs Croatia
Actual Result: Brazil 3 - 1 Croatia
Matchup: Brazil vs Croatia
---------------------------------
Brazil Win Probability: 54.7 %
Draw Probability: 14.8 %
Croatia Win Probability: 30.5 %
---------------------------------
Simulated Scoreline: Brazil 4 - 1 Croatia
----------------------------------------

Match #19: Brazil vs Panama
Actual Result: Brazil 6 - 2 Panama
Matchup: Brazil vs Panama
---------------------------------
Brazil Win Probability: 87.6 %
Draw Probability: 6.8 %
Panama Win Probability: 5.6 %
---------------------------------
Simulated Scoreline: Brazil 3 - 1 Panama
----------------------------------------

Match #20: Brazil vs Senegal
Actual Result: Brazil 2 - 0 Senegal
Matchup: Brazil vs Senegal
---------------------------------
Brazil Win Probability: 56.7 %
Draw Probability: 15.6 %
Senegal Win Probability: 27.7 %
---------------------------------
Simulated Scoreline: Brazil 2 - 0 Senegal
----------------------------------------

Match #21: Brazil vs Tunisia
Actual Result: Brazil 1 - 1 Tunisia
Matchup: Brazil vs Tunisia
---------------------------------
Brazil Win Probability: 82.8 %
Draw Probability: 8.6 %
Tunisia Win Probability: 8.6 %
---------------------------------
Simulated Scoreline: Brazil 1 - 0 Tunisia
----------------------------------------

Match #22: Netherlands vs Norway
Actual Result: Netherlands 2 - 1 Norway
Matchup: Netherlands vs Norway
---------------------------------
Netherlands Win Probability: 75.5 %
Draw Probability: 11.3 %
Norway Win Probability: 13.2 %
---------------------------------
Simulated Scoreline: Netherlands 3 - 2 Norway
----------------------------------------

Match #23: Netherlands vs Ecuador
Actual Result: Netherlands 1 - 1 Ecuador
Matchup: Netherlands vs Ecuador
---------------------------------
Netherlands Win Probability: 77.2 %
Draw Probability: 9.5 %
Ecuador Win Probability: 13.3 %
---------------------------------
Simulated Scoreline: Netherlands 2 - 1 Ecuador
----------------------------------------

Match #24: Egypt vs Saudi Arabia
Actual Result: Egypt 4 - 0 Saudi Arabia
Matchup: Egypt vs Saudi Arabia
---------------------------------
Egypt Win Probability: 52.2 %
Draw Probability: 16.1 %
Saudi Arabia Win Probability: 31.7 %
---------------------------------
Simulated Scoreline: Egypt 0 - 1 Saudi Arabia
----------------------------------------

Match #25: Egypt vs Jordan
Actual Result: Egypt 0 - 3 Jordan
Matchup: Egypt vs Jordan
---------------------------------
Egypt Win Probability: 76.7 %
Draw Probability: 11.9 %
Jordan Win Probability: 11.4 %
---------------------------------
Simulated Scoreline: Egypt 0 - 0 Jordan
----------------------------------------

Match #26: Egypt vs Senegal
Actual Result: Egypt 0 - 1 Senegal
Matchup: Egypt vs Senegal
---------------------------------
Egypt Win Probability: 27.1 %
Draw Probability: 16.9 %
Senegal Win Probability: 56.0 %
---------------------------------
Simulated Scoreline: Egypt 1 - 1 Senegal
----------------------------------------

Match #27: Egypt vs Ivory Coast
Actual Result: Egypt 3 - 2 Ivory Coast
Matchup: Egypt vs Ivory Coast
---------------------------------
Egypt Win Probability: 39.4 %
Draw Probability: 16.4 %
Ivory Coast Win Probability: 44.2 %
---------------------------------
Simulated Scoreline: Egypt 0 - 1 Ivory Coast
----------------------------------------

Match #28: Haiti vs Saudi Arabia
Actual Result: Haiti 0 - 1 Saudi Arabia
Matchup: Haiti vs Saudi Arabia
---------------------------------
Haiti Win Probability: 40.9 %
Draw Probability: 14.9 %
Saudi Arabia Win Probability: 44.2 %
---------------------------------
Simulated Scoreline: Haiti 3 - 2 Saudi Arabia
----------------------------------------

Match #29: Haiti vs USA
Actual Result: Haiti 1 - 2 USA
Matchup: Haiti vs USA
---------------------------------
Haiti Win Probability: 23.3 %
Draw Probability: 15.4 %
USA Win Probability: 61.3 %
---------------------------------
Simulated Scoreline: Haiti 0 - 1 USA
----------------------------------------

Match #30: Haiti vs Tunisia
Actual Result: Haiti 0 - 1 Tunisia
Matchup: Haiti vs Tunisia
---------------------------------
Haiti Win Probability: 33.4 %
Draw Probability: 15.2 %
Tunisia Win Probability: 51.4 %
---------------------------------
Simulated Scoreline: Haiti 1 - 2 Tunisia
----------------------------------------

In [67]:
import pickle

# 1. Save the trained Random Forest Regressor brain
with open('world_cup_model.pkl', 'wb') as model_file:
    pickle.dump(best_rf_regressor, model_file)

# 2. Save your clean DataFrame so Streamlit has access to the team stats
new_df.to_csv('streamlit_teams.csv', index=False)

print("✅ Model and team data saved successfully via Pickle!")

✅ Model and team data saved successfully via Pickle!

In [74]:
sorted(list(new_df['team'].values))

['Algeria',
 'Argentina',
 'Australia',
 'Austria',
 'Belgium',
 'Bosnia-Herzegovina',
 'Brazil',
 'Canada',
 'Cape Verde',
 'Colombia',
 'Croatia',
 'Curacao',
 'Czechia',
 'DR Congo',
 'Ecuador',
 'Egypt',
 'England',
 'France',
 'Germany',
 'Ghana',
 'Haiti',
 'Iran',
 'Iraq',
 'Ivory Coast',
 'Japan',
 'Jordan',
 'Mexico',
 'Morocco',
 'Netherlands',
 'New Zealand',
 'Norway',
 'Panama',
 'Paraguay',
 'Portugal',
 'Qatar',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'South Africa',
 'South Korea',
 'Spain',
 'Sweden',
 'Switzerland',
 'Tunisia',
 'Turkiye',
 'USA',
 'Uruguay',
 'Uzbekistan']